//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type PharmaSheetMedicineBrands struct {
	ID              uuid.UUID `sql:"primary_key"`
	MedicationID    string
	TradeID         string
	TradeName       *string
	BlisterImageURL *string
	TabletImageURL  *string
	BoxImageURL     *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
