//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PharmaSheetWarehouseSheets struct {
	WarehouseID                         string `sql:"primary_key"`
	SpreadsheetID                       string
	MedicineSheetID                     int32
	MedicineSheetName                   string
	MedicineBrandSheetID                int32
	MedicineBrandSheetName              string
	MedicineHouseSheetID                int32
	MedicineHouseSheetName              string
	MedicineBlisterDateHistorySheetID   int32
	MedicineBlisterDateHistorySheetName string
	LatestSyncedAt                      time.Time
	CreatedAt                           time.Time
}
