//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type PharmaSheetApprovalStatus string

const (
	PharmaSheetApprovalStatus_Approved PharmaSheetApprovalStatus = "APPROVED"
	PharmaSheetApprovalStatus_Pending  PharmaSheetApprovalStatus = "PENDING"
)

var PharmaSheetApprovalStatusAllValues = []PharmaSheetApprovalStatus{
	PharmaSheetApprovalStatus_Approved,
	PharmaSheetApprovalStatus_Pending,
}

func (e *PharmaSheetApprovalStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "APPROVED":
		*e = PharmaSheetApprovalStatus_Approved
	case "PENDING":
		*e = PharmaSheetApprovalStatus_Pending
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for PharmaSheetApprovalStatus enum")
	}

	return nil
}

func (e PharmaSheetApprovalStatus) String() string {
	return string(e)
}
