//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PharmaSheetMedicineBrands struct {
	MedicineBrandID string `sql:"primary_key"`
	MedicationID    string
	BrandName       string
	BlisterImageURL *string
	TabletImageURL  *string
	BoxImageURL     *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
