//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type PharmaSheetMedicineHouses struct {
	ID           uuid.UUID `sql:"primary_key"`
	WarehouseID  string
	MedicationID string
	Locker       string
	Floor        int32
	No           int32
	Label        *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
