//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PharmaSheetMedicineHouses struct {
	WarehouseID       string
	MedicineBrandID   string
	Locker            string
	Floor             int32
	No                int32
	BlisterChangeDate *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
