//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PharmaSheetMedicines struct {
	MedicationID string `sql:"primary_key"`
	MedicalName  string
	Label        *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
