//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Role string

const (
	Role_Admin  Role = "ADMIN"
	Role_Editor Role = "EDITOR"
	Role_Viewer Role = "VIEWER"
)

var RoleAllValues = []Role{
	Role_Admin,
	Role_Editor,
	Role_Viewer,
}

func (e *Role) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "ADMIN":
		*e = Role_Admin
	case "EDITOR":
		*e = Role_Editor
	case "VIEWER":
		*e = Role_Viewer
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Role enum")
	}

	return nil
}

func (e Role) String() string {
	return string(e)
}
