//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type WarehouseUsers struct {
	WarehouseID uuid.UUID
	UserID      uuid.UUID
	Role        Role
	CreatedAt   time.Time
	UpdatedAt   *time.Time
	Status      ApprovalStatus
}
