//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Warehouses = newWarehousesTable("public", "warehouses", "")

type warehousesTable struct {
	postgres.Table

	// Columns
	WarehouseID postgres.ColumnString
	Name        postgres.ColumnString
	CreatedAt   postgres.ColumnTimestampz
	UpdatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type WarehousesTable struct {
	warehousesTable

	EXCLUDED warehousesTable
}

// AS creates new WarehousesTable with assigned alias
func (a WarehousesTable) AS(alias string) *WarehousesTable {
	return newWarehousesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new WarehousesTable with assigned schema name
func (a WarehousesTable) FromSchema(schemaName string) *WarehousesTable {
	return newWarehousesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new WarehousesTable with assigned table prefix
func (a WarehousesTable) WithPrefix(prefix string) *WarehousesTable {
	return newWarehousesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new WarehousesTable with assigned table suffix
func (a WarehousesTable) WithSuffix(suffix string) *WarehousesTable {
	return newWarehousesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newWarehousesTable(schemaName, tableName, alias string) *WarehousesTable {
	return &WarehousesTable{
		warehousesTable: newWarehousesTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newWarehousesTableImpl("", "excluded", ""),
	}
}

func newWarehousesTableImpl(schemaName, tableName, alias string) warehousesTable {
	var (
		WarehouseIDColumn = postgres.StringColumn("warehouse_id")
		NameColumn        = postgres.StringColumn("name")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampzColumn("updated_at")
		allColumns        = postgres.ColumnList{WarehouseIDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{NameColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return warehousesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		WarehouseID: WarehouseIDColumn,
		Name:        NameColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
