//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var PharmaSheetRole = &struct {
	Admin  postgres.StringExpression
	Editor postgres.StringExpression
	Viewer postgres.StringExpression
}{
	Admin:  postgres.NewEnumValue("ADMIN"),
	Editor: postgres.NewEnumValue("EDITOR"),
	Viewer: postgres.NewEnumValue("VIEWER"),
}
