//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PharmaSheetWarehouseUsers = newPharmaSheetWarehouseUsersTable("public", "pharma_sheet_warehouse_users", "")

type pharmaSheetWarehouseUsersTable struct {
	postgres.Table

	// Columns
	WarehouseID postgres.ColumnString
	UserID      postgres.ColumnString
	Role        postgres.ColumnString
	Status      postgres.ColumnString
	CreatedAt   postgres.ColumnTimestampz
	UpdatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PharmaSheetWarehouseUsersTable struct {
	pharmaSheetWarehouseUsersTable

	EXCLUDED pharmaSheetWarehouseUsersTable
}

// AS creates new PharmaSheetWarehouseUsersTable with assigned alias
func (a PharmaSheetWarehouseUsersTable) AS(alias string) *PharmaSheetWarehouseUsersTable {
	return newPharmaSheetWarehouseUsersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PharmaSheetWarehouseUsersTable with assigned schema name
func (a PharmaSheetWarehouseUsersTable) FromSchema(schemaName string) *PharmaSheetWarehouseUsersTable {
	return newPharmaSheetWarehouseUsersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PharmaSheetWarehouseUsersTable with assigned table prefix
func (a PharmaSheetWarehouseUsersTable) WithPrefix(prefix string) *PharmaSheetWarehouseUsersTable {
	return newPharmaSheetWarehouseUsersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PharmaSheetWarehouseUsersTable with assigned table suffix
func (a PharmaSheetWarehouseUsersTable) WithSuffix(suffix string) *PharmaSheetWarehouseUsersTable {
	return newPharmaSheetWarehouseUsersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPharmaSheetWarehouseUsersTable(schemaName, tableName, alias string) *PharmaSheetWarehouseUsersTable {
	return &PharmaSheetWarehouseUsersTable{
		pharmaSheetWarehouseUsersTable: newPharmaSheetWarehouseUsersTableImpl(schemaName, tableName, alias),
		EXCLUDED:                       newPharmaSheetWarehouseUsersTableImpl("", "excluded", ""),
	}
}

func newPharmaSheetWarehouseUsersTableImpl(schemaName, tableName, alias string) pharmaSheetWarehouseUsersTable {
	var (
		WarehouseIDColumn = postgres.StringColumn("warehouse_id")
		UserIDColumn      = postgres.StringColumn("user_id")
		RoleColumn        = postgres.StringColumn("role")
		StatusColumn      = postgres.StringColumn("status")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampzColumn("updated_at")
		allColumns        = postgres.ColumnList{WarehouseIDColumn, UserIDColumn, RoleColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{WarehouseIDColumn, UserIDColumn, RoleColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return pharmaSheetWarehouseUsersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		WarehouseID: WarehouseIDColumn,
		UserID:      UserIDColumn,
		Role:        RoleColumn,
		Status:      StatusColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
