//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PharmaSheetMedicines = newPharmaSheetMedicinesTable("public", "pharma_sheet_medicines", "")

type pharmaSheetMedicinesTable struct {
	postgres.Table

	// Columns
	MedicineID  postgres.ColumnString
	WarehouseID postgres.ColumnString
	LockerID    postgres.ColumnString
	Floor       postgres.ColumnInteger
	No          postgres.ColumnInteger
	Address     postgres.ColumnString
	Description postgres.ColumnString
	MedicalName postgres.ColumnString
	Label       postgres.ColumnString
	ImageURL    postgres.ColumnString
	CreatedAt   postgres.ColumnTimestampz
	UpdatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PharmaSheetMedicinesTable struct {
	pharmaSheetMedicinesTable

	EXCLUDED pharmaSheetMedicinesTable
}

// AS creates new PharmaSheetMedicinesTable with assigned alias
func (a PharmaSheetMedicinesTable) AS(alias string) *PharmaSheetMedicinesTable {
	return newPharmaSheetMedicinesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PharmaSheetMedicinesTable with assigned schema name
func (a PharmaSheetMedicinesTable) FromSchema(schemaName string) *PharmaSheetMedicinesTable {
	return newPharmaSheetMedicinesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PharmaSheetMedicinesTable with assigned table prefix
func (a PharmaSheetMedicinesTable) WithPrefix(prefix string) *PharmaSheetMedicinesTable {
	return newPharmaSheetMedicinesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PharmaSheetMedicinesTable with assigned table suffix
func (a PharmaSheetMedicinesTable) WithSuffix(suffix string) *PharmaSheetMedicinesTable {
	return newPharmaSheetMedicinesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPharmaSheetMedicinesTable(schemaName, tableName, alias string) *PharmaSheetMedicinesTable {
	return &PharmaSheetMedicinesTable{
		pharmaSheetMedicinesTable: newPharmaSheetMedicinesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newPharmaSheetMedicinesTableImpl("", "excluded", ""),
	}
}

func newPharmaSheetMedicinesTableImpl(schemaName, tableName, alias string) pharmaSheetMedicinesTable {
	var (
		MedicineIDColumn  = postgres.StringColumn("medicine_id")
		WarehouseIDColumn = postgres.StringColumn("warehouse_id")
		LockerIDColumn    = postgres.StringColumn("locker_id")
		FloorColumn       = postgres.IntegerColumn("floor")
		NoColumn          = postgres.IntegerColumn("no")
		AddressColumn     = postgres.StringColumn("address")
		DescriptionColumn = postgres.StringColumn("description")
		MedicalNameColumn = postgres.StringColumn("medical_name")
		LabelColumn       = postgres.StringColumn("label")
		ImageURLColumn    = postgres.StringColumn("image_url")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampzColumn("updated_at")
		allColumns        = postgres.ColumnList{MedicineIDColumn, WarehouseIDColumn, LockerIDColumn, FloorColumn, NoColumn, AddressColumn, DescriptionColumn, MedicalNameColumn, LabelColumn, ImageURLColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{WarehouseIDColumn, LockerIDColumn, FloorColumn, NoColumn, AddressColumn, DescriptionColumn, MedicalNameColumn, LabelColumn, ImageURLColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return pharmaSheetMedicinesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		MedicineID:  MedicineIDColumn,
		WarehouseID: WarehouseIDColumn,
		LockerID:    LockerIDColumn,
		Floor:       FloorColumn,
		No:          NoColumn,
		Address:     AddressColumn,
		Description: DescriptionColumn,
		MedicalName: MedicalNameColumn,
		Label:       LabelColumn,
		ImageURL:    ImageURLColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
