//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PharmaSheetLockers = newPharmaSheetLockersTable("public", "pharma_sheet_lockers", "")

type pharmaSheetLockersTable struct {
	postgres.Table

	// Columns
	LockerID    postgres.ColumnString
	WarehouseID postgres.ColumnString
	Name        postgres.ColumnString
	CreatedAt   postgres.ColumnTimestampz
	UpdatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PharmaSheetLockersTable struct {
	pharmaSheetLockersTable

	EXCLUDED pharmaSheetLockersTable
}

// AS creates new PharmaSheetLockersTable with assigned alias
func (a PharmaSheetLockersTable) AS(alias string) *PharmaSheetLockersTable {
	return newPharmaSheetLockersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PharmaSheetLockersTable with assigned schema name
func (a PharmaSheetLockersTable) FromSchema(schemaName string) *PharmaSheetLockersTable {
	return newPharmaSheetLockersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PharmaSheetLockersTable with assigned table prefix
func (a PharmaSheetLockersTable) WithPrefix(prefix string) *PharmaSheetLockersTable {
	return newPharmaSheetLockersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PharmaSheetLockersTable with assigned table suffix
func (a PharmaSheetLockersTable) WithSuffix(suffix string) *PharmaSheetLockersTable {
	return newPharmaSheetLockersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPharmaSheetLockersTable(schemaName, tableName, alias string) *PharmaSheetLockersTable {
	return &PharmaSheetLockersTable{
		pharmaSheetLockersTable: newPharmaSheetLockersTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newPharmaSheetLockersTableImpl("", "excluded", ""),
	}
}

func newPharmaSheetLockersTableImpl(schemaName, tableName, alias string) pharmaSheetLockersTable {
	var (
		LockerIDColumn    = postgres.StringColumn("locker_id")
		WarehouseIDColumn = postgres.StringColumn("warehouse_id")
		NameColumn        = postgres.StringColumn("name")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampzColumn("updated_at")
		allColumns        = postgres.ColumnList{LockerIDColumn, WarehouseIDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{WarehouseIDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return pharmaSheetLockersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		LockerID:    LockerIDColumn,
		WarehouseID: WarehouseIDColumn,
		Name:        NameColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
